# Generated by Django 4.1.4 on 2023-04-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproducts',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
