# Generated by Django 4.1.4 on 2023-04-21 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_remove_savedproducts_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='product_name',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='savedproducts',
            old_name='product_name',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='soldoutproducts',
            old_name='product_name',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='savedproducts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
