# Generated by Django 4.1.4 on 2023-04-21 04:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_rename_product_products_product_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Savedproducts',
            new_name='carts',
        ),
    ]
